dependencies:
  build:
    - ruby:2.6.0

build_targets:
  - name: release
    commands:
      - gem install bundler
      - bundle install
      - gem build yourbase-rspec-skipper.gemspec
      - gem push *.gem


  - name: test
    commands:
      - gem install bundler
      - bundle install 
      - bundle exec rake


ci:
  builds:
    - name: run_tests
      build_target: test

    - name: do_release
      build_target: release
      when: tagged IS true
