dependencies:
  build:
    - ruby:2.4.5

build_targets:
  - name: release
    commands:
      - gem install bundler
      - bundle install
      - bundle exec rake release 

  - name: test
    commands:
      - gem install bundler
      - bundle install 
      - bundle exec rake


ci:
  builds:
    - name: run_tests
      build_target: test

    - name: do_release
      build_target: release
      when: tagged IS true
